name: fast_qr_reader_view
description: Forked multi-code reader widget with live preview for both iOS and Android. Using native code for detection, scans QR, PDF417 and CODE39 among others.
author: Laurent Mignot <laurent@shapedigital.io>
homepage: https://github.com/EasyAdminApp/fast_qr_reader_view
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: co.apperto.fastqrreaderview
    pluginClass: FastQrReaderViewPlugin
